apiVersion: v1
kind: Service
metadata:
    name: gestion-service-back
    labels:
      app: gestion
spec:
    ports:
      - port: 9090
        protocol: "TCP"
    selector:
      app: gestion
    type: NodePort
