apiVersion: v1
kind: Service
metadata:
    name: gestion-service
    labels:
      app: gestion
spec:
    ports:
      - port: 80
        protocol: "TCP"
    selector:
      app: gestion
    type: NodePort
